version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mvc_mysql
    restart: always
    environment:
      MYSQL_DATABASE: mvc
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
